# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nightly
on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'TTT.*/**'
      - '.github/workflows/nightly.yml'
  schedule:
    - cron: '15 0 * * 3' # Every Wednesday at 00:15 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          show-progress: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - run: |
          dotnet restore TTT.Plugin/TTT.Plugin.csproj
          dotnet build TTT.Plugin/TTT.Plugin.csproj --no-restore
          dotnet publish TTT.Plugin/TTT.Plugin.csproj --no-build --no-restore

      - uses: actions/upload-artifact@v4.0.0
        with:
          name: ttt-nightly
          path: build/TTT
          if-no-files-found: error
  post_webhook:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: POST Webhook
        run: |
          curl -X POST \
            --fail \
            -F token=${{ secrets.GITLAB_SECRET_TOKEN }} \
            -F ref=dev \
            https://gitlab.edgegamers.io/api/v4/projects/2594/trigger/pipeline
