name: Release on Tag

on:
  push:
    tags:
      - "*"   # runs for any pushed tag

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: "5.x"

      - name: Determine version with GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3

      - name: Build Locale
        shell: bash
        run: |
          mkdir -p build/TTT/lang
          dotnet restore Locale/Locale.csproj
          dotnet build Locale/Locale.csproj --no-restore -c Release
          shopt -s nullglob
          files=(lang/*.json)
          if [ ${#files[@]} -gt 0 ]; then
            cp "${files[@]}" build/TTT/lang/
          fi

      - name: Publish Plugin
        run: |
          dotnet restore TTT/Plugin/Plugin.csproj
          dotnet publish TTT/Plugin/Plugin.csproj --no-restore -c Release -o build/TTT

      - name: Package ZIP
        shell: bash
        run: |
          FULL="${{ steps.gitversion.outputs.FullSemVer }}"
          cd build/TTT
          zip -r "../TTT-${FULL}.zip" .
          cd -

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TTT-${{ steps.gitversion.outputs.FullSemVer }}
          path: build/TTT-${{ steps.gitversion.outputs.FullSemVer }}.zip
          if-no-files-found: error

      - name: Check if tag commit is on main
        id: branch_check
        shell: bash
        run: |
          if git branch -r --contains "$GITHUB_SHA" | grep -qE 'origin/main'; then
            echo "is_main=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_main=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Find previous tag
        id: prev
        shell: bash
        run: |
          git fetch --tags --force
          PREV=$(git describe --tags --abbrev=0 "${GITHUB_SHA}^" 2>/dev/null || true)
          if [ -z "$PREV" ]; then
            PREV=$(git tag --sort=-creatordate | grep -v -x "${GITHUB_REF_NAME}" | head -n 1 || true)
          fi
          echo "prev_tag=$PREV" >> "$GITHUB_OUTPUT"

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          TAG="${{ steps.gitversion.outputs.SemVer }}"           # release tag from GitVersion
          FULL="${{ steps.gitversion.outputs.FullSemVer }}"     # for asset name
          ASSET="build/TTT-${FULL}.zip"
          TITLE="$TAG"

          PRERELEASE_FLAG=""
          if [ "${{ steps.branch_check.outputs.is_main }}" != "true" ]; then
            PRERELEASE_FLAG="--prerelease"
          fi

          NOTES_ARGS="--generate-notes"
          if [ -n "${{ steps.prev.outputs.prev_tag }}" ]; then
            NOTES_ARGS="$NOTES_ARGS --notes-start-tag ${{ steps.prev.outputs.prev_tag }}"
          fi

          test -f "$ASSET" || { echo "Asset not found: $ASSET"; exit 1; }

          gh release create "$TAG" "$ASSET" \
            --title "$TITLE" \
            $PRERELEASE_FLAG \
            $NOTES_ARGS \
            --target "$GITHUB_SHA"
