name: Release

on:
  workflow_run:
    workflows: [ "Nightly" ]
    types:
      - completed
    branches:
      - main
      - dev

concurrency:
  group: release-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      pull-requests: read

    steps:
      - name: Extract Triggering Branch
        id: extract_branch
        run: echo "branch=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v4.0.1
        with:
          versionSpec: '6.3.x'

      - name: Run GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v4.0.1

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          name: TTT
          workflow: 'nightly.yml'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          skip_unpack: 'true'
          path: 'build'
          
      - name: Rename artifact
        run: |
          mkdir -p build
          mv build/TTT build/TTT-${{ steps.gitversion.outputs.fullSemVer }}.zip

      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5

      - name: Create GitHub Release
        if: ${{ steps.extract_branch.outputs.branch == 'main' || steps.extract_branch.outputs.branch == 'dev' }}
        uses: softprops/action-gh-release@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          name: ${{ steps.gitversion.outputs.fullSemVer }}
          tag_name: ${{ steps.gitversion.outputs.fullSemVer }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.extract_branch.outputs.branch == 'dev' }}
          files: build/TTT-${{ steps.gitversion.outputs.fullSemVer }}.zip